/**
 * GANESH – THE JOURNEY
 * Configuration & Metadata for all 3 Worlds and 18 Playable Levels
 */

export const GAME_CONFIG = {
  TITLE: "GANESH – THE JOURNEY",
  VIRTUAL_WIDTH: 1280,
  VIRTUAL_HEIGHT: 720,
  FPS: 60,
  PLAYER_SPEED: 260,
  MAX_WORLDS: 3,
  LEVELS_PER_WORLD: 6,
  TOTAL_LEVELS: 18,
};

export const WORLDS_DATA = [
  {
    id: 1,
    key: "mythology",
    title: "WORLD 1: MYTHOLOGY WORLD",
    shortTitle: "Mythology World",
    tagline: "The Divine Tales of Lord Ganesha",
    description: "Experience the revered mythological stories of Lord Ganesha: his birth, his sacred bond with Mushika, the supreme circumambulation of Kailash, Chandra's lesson in humility, and the holy farewell.",
    bgTheme: "kailash",
    bannerCompletion: "MYTHOLOGY WORLD COMPLETE — 6/6 LEVELS",
    levels: [
      {
        id: 1,
        worldId: 1,
        number: 1,
        title: "Birth of Vinayaka",
        subtitle: "The Sacred Guardian of Kailash",
        description: "Mother Parvati entrusts Vinayaka with guarding the entrance to Kailash. Inspect five arriving visitors, solve deduction puzzles, and welcome Lord Shiva.",
        objective: "Guard the sacred gate & solve visitor deduction puzzles",
        hint: "Observe each visitor's sacred symbols, offerings, and demeanor before deciding.",
        type: "puzzle_guardian",
        targetVisitors: 5,
        targetScore: 1500,
        hasMeter: true,
      },
      {
        id: 2,
        worldId: 1,
        number: 2,
        title: "Mushikasura",
        subtitle: "From Rampaging Giant to Divine Companion",
        description: "A giant mouse causes disruption in Kailash. Search for clues, dodge obstacles in a thrilling chase, outsmart him peacefully, and welcome him as Vinayaka's mouse companion.",
        objective: "Find 3 clues, pursue Mushikasura, and outsmart him",
        hint: "Follow the modak crumbs and footprints, then dodge obstacles during the chase.",
        type: "chase_transformation",
        targetClues: 3,
        targetScore: 1600,
        hasMeter: false,
      },
      {
        id: 3,
        worldId: 1,
        number: 3,
        title: "The Three Rounds",
        subtitle: "Wisdom Transcends the Universe",
        description: "Shiva and Parvati present a challenge: circle the universe first to win the divine fruit of wisdom. While Subrahmanya takes flight on his peacock, Vinayaka realizes where the universe truly resides.",
        objective: "Perform 3 sacred pradakshinas around Shiva and Parvati",
        hint: "To a loving child, parents embody the entire universe. Complete 3 respectful rounds.",
        type: "circumambulation_wisdom",
        targetRounds: 3,
        targetScore: 1500,
        hasMeter: false,
      },
      {
        id: 4,
        worldId: 1,
        number: 4,
        title: "The Celebration",
        subtitle: "Joy and Offerings in Kailash",
        description: "Celebrate Vinayaka's wisdom! Gather sweet modaks and fresh red hibiscus flowers, arrange vibrant rangolis and brass diyas, and participate in a festive divine aarti.",
        objective: "Collect 8 modaks, 10 flowers, and light the sacred lamps",
        hint: "Explore the scenic pathways of Kailash and place decorations at the altar.",
        type: "collection_decoration",
        targetModaks: 8,
        targetFlowers: 10,
        targetScore: 1800,
        hasMeter: false,
      },
      {
        id: 5,
        worldId: 1,
        number: 5,
        title: "The Moon's Curse",
        subtitle: "A Sacred Lesson in Humility",
        description: "While travelling under the moonlit sky, Mushika stumbles and modaks scatter. When Chandra laughs mockingly from above, Vinayaka imparts a profound lesson on humility before granting peaceful redemption.",
        objective: "Gather the scattered modaks and teach Chandra true humility",
        hint: "Recover the sacred offerings and interact with Chandra to show the consequence of pride.",
        type: "moon_redemption",
        targetModaks: 6,
        targetScore: 1500,
        hasMeter: false,
      },
      {
        id: 6,
        worldId: 1,
        number: 6,
        title: "The Final Journey",
        subtitle: "Sacred Procession and Peaceful Visarjan",
        description: "Join the devotees in a celebratory village procession. Clear the path, assist pilgrims with offerings, and arrive at the holy river ghat for a peaceful, sunset Visarjan.",
        objective: "Complete the 4 sacred phases of the farewell journey",
        hint: "Help the devotees along the path and accompany Vinayaka to the holy water.",
        type: "visarjan_procession",
        targetScore: 2000,
        hasMeter: false,
      }
    ]
  },
  {
    id: 2,
    key: "history",
    title: "WORLD 2: HISTORY WORLD",
    shortTitle: "History World",
    tagline: "Tracing Cultural & Historical Evolution",
    description: "Explore the historical development of Ganesh Chaturthi through verified cultural milestones, from ancient Vedic hymns and Maratha heritage to the 1893 Sarvajanik community movement.",
    bgTheme: "heritage",
    bannerCompletion: "HISTORY WORLD COMPLETE — 6/6 LEVELS",
    levels: [
      {
        id: 7,
        worldId: 2,
        number: 1,
        title: "Roots of the Festival",
        subtitle: "Ancient Vedic & Cultural Foundations",
        description: "Explore an ancient cultural landscape. Discover early epigraphs, Rigvedic references to Ganapati as the patron of arts and wisdom, and match seasonal harvest traditions.",
        objective: "Discover 4 historical artifacts and solve the ancient symbol puzzle",
        hint: "Inspect the ancient pillars and decipher the connection to agricultural harvest cycles.",
        type: "history_explore",
        targetArtifacts: 4,
        targetScore: 1400,
      },
      {
        id: 8,
        worldId: 2,
        number: 2,
        title: "Festival Takes Shape",
        subtitle: "From Household Shrine to Community Unity",
        description: "Witness how celebrations evolved through the Satavahana and Rashtrakuta eras, and learn how Lokmanya Bal Gangadhar Tilak in 1893 pioneered the public Sarvajanik festival to foster national solidarity.",
        objective: "Explore historical panels and sequence the chronological timeline",
        hint: "Arrange the milestone years in proper sequence: Ancient -> Medieval -> 1893.",
        type: "history_timeline",
        targetScore: 1500,
      },
      {
        id: 9,
        worldId: 2,
        number: 3,
        title: "Community Celebration",
        subtitle: "Pandal Architecture and Social Cooperation",
        description: "Step into an authentic 20th-century community mandap. Help volunteers arrange stage lighting, prepare traditional musical instruments (dhol-tasha), and distribute prasad peacefully.",
        objective: "Complete 3 community cooperation tasks and organize the pandal",
        hint: "Cooperate with the festival volunteers and place the stage instruments in harmony.",
        type: "community_cooperation",
        targetScore: 1600,
      },
      {
        id: 10,
        worldId: 2,
        number: 4,
        title: "Journey Through Time",
        subtitle: "Four Eras of Cultural Heritage",
        description: "Travel through four distinct historical time periods: Ancient Vedic, Medieval Maratha under Shivaji Maharaj, 1893 Public Renaissance, and Contemporary Eco-Conscious Celebrations.",
        objective: "Visit all 4 eras and collect their representative cultural seals",
        hint: "Each era highlights a unique contribution to the living festival heritage.",
        type: "history_time_travel",
        targetEras: 4,
        targetScore: 1700,
      },
      {
        id: 11,
        worldId: 2,
        number: 5,
        title: "Traditions Across Generations",
        subtitle: "Diverse Regional Expressions of Devotion",
        description: "Discover how Ganesh Chaturthi is celebrated with distinct warmth across Maharashtra, Tamil Nadu, Karnataka, and Telangana. Match cultural offerings with their traditional regional significance.",
        objective: "Match 4 regional tradition sets and assemble the inter-state tapestry",
        hint: "Notice regional specialties: Modak & Puran Poli, Kozhukattai, Kudumu, and Grand Mandaps.",
        type: "regional_traditions",
        targetRegions: 4,
        targetScore: 1600,
      },
      {
        id: 12,
        worldId: 2,
        number: 6,
        title: "Living Heritage",
        subtitle: "A Continuing Legacy of Unity & Art",
        description: "Synthesize everything learned into a vibrant living heritage pandal. Set up cultural workshops, eco-friendly awareness booths, and celebrate the enduring unity of the festival.",
        objective: "Solve the master cultural riddle and open the Living Heritage Mandap",
        hint: "Use wisdom gathered from all eras: faith, unity, cultural art, and ecological care.",
        type: "history_master",
        targetScore: 2000,
      }
    ]
  },
  {
    id: 3,
    key: "sculpture",
    title: "WORLD 3: SCULPTURE WORLD",
    shortTitle: "Sculpture World",
    tagline: "Eco-Friendly Clay Art & Sacred Crafting",
    description: "Experience the pure, meditative joy of sculpting a traditional eco-friendly Ganesha murti from natural river clay (Shaadu mati), detailing his sacred forms, and celebrating with traditional aarti.",
    bgTheme: "workshop",
    bannerCompletion: "SCULPTURE WORLD COMPLETE — 6/6 LEVELS",
    levels: [
      {
        id: 13,
        worldId: 3,
        number: 1,
        title: "Choose Clay",
        subtitle: "Selecting Sacred Eco-Friendly Earth",
        description: "Learn about traditional eco-friendly materials. Choose natural Shaadu river clay over plaster of Paris, knead with pure water, and prepare a soft, smooth clay mound for sculpting.",
        objective: "Select eco-friendly Shaadu clay and knead to perfect texture",
        hint: "Natural Shaadu mati dissolves harmlessly in water, returning respectfully to nature.",
        type: "sculpture_clay",
        targetScore: 1400,
      },
      {
        id: 14,
        worldId: 3,
        number: 2,
        title: "Shape the Form",
        subtitle: "Building the Sacred Silhouette",
        description: "Form the foundation of the murti step by step: sculpt the sacred lotus base, the peaceful seated torso (Lambodara), the graceful head, and the gentle curved trunk.",
        objective: "Assemble and smooth the 4 primary anatomical forms",
        hint: "Follow the traditional proportions: sturdy base, benevolent belly, and curved trunk.",
        type: "sculpture_shape",
        targetScore: 1500,
      },
      {
        id: 15,
        worldId: 3,
        number: 3,
        title: "Add Details",
        subtitle: "Iconography of Wisdom & Grace",
        description: "Carve the profound iconographic details: the large listening ears, the broken tusk (Ekadanta), the grand crown (Mukut), the sweet modak in palm, and the Abhaya mudra of fearlessness.",
        objective: "Incorporate 5 sacred details and inspect their symmetry",
        hint: "Each detail holds meaning: large ears listen to prayers, broken tusk symbolises sacrifice.",
        type: "sculpture_details",
        targetScore: 1600,
      },
      {
        id: 16,
        worldId: 3,
        number: 4,
        title: "Colours and Patterns",
        subtitle: "Natural Pigments and Sacred Rangoli",
        description: "Bring the murti to life using organic, biodegradable pigments: bright turmeric yellow, auspicious vermilion red, sacred sandalwood paste, and delicate golden linework.",
        objective: "Paint the sacred attire, forehead tilak, and decorative borders",
        hint: "Use natural pigments that celebrate nature without polluting sacred waterways.",
        type: "sculpture_paint",
        targetScore: 1700,
      },
      {
        id: 17,
        worldId: 3,
        number: 5,
        title: "Prepare the Celebration",
        subtitle: "Sanctifying the Altar & Offerings",
        description: "Prepare the shrine for the completed sculpture. Drape festive mango leaf torans, arrange banana stems, light flickering brass diyas, and present fresh durva grass and modaks.",
        objective: "Decorate the sanctum and arrange the 5 sacred offerings",
        hint: "Place lamps at both corners and lay the garland of red hibiscus around the altar.",
        type: "sculpture_altar",
        targetScore: 1800,
      },
      {
        id: 18,
        worldId: 3,
        number: 6,
        title: "Completed Creation",
        subtitle: "Divine Darshan, Aarti & Blessings",
        description: "Behold your completed handcrafted creation in radiant glory! Light the camphor flame, offer the prayer hymn, ring the temple bell, and receive divine blessings of peace and joy.",
        objective: "Perform the final divine aarti and receive Ganesha's blessings",
        hint: "Ring the temple bell and wave the sacred aarti lamp in gentle circular motions.",
        type: "sculpture_darshan",
        targetScore: 2000,
      }
    ]
  }
];
